import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";
import { styled } from "@stitches/react";
import { useTheme } from "next-themes";
const Text = styled("p", {
  fontFamily: "$system",
  color: "$hiContrast",

  variants: {
    size: {
      1: {
        fontSize: "$1",
      },
      2: {
        fontSize: "$2",
      },
      3: {
        fontSize: "$3",
      },
    },
  },
});

const Button = styled("button", {
  appearance: "none",
  border: "none",
  height: 25,
  fontSize: 13,
  borderRadius: "24px",

  variants: {
    variant: {
      gray: {
        backgroundColor: "Gainsboro",
        "&:hover": {
          backgroundColor: "LightGray",
        },
      },
      purple: {
        backgroundColor: "BlueViolet",
        "&:hover": {
          backgroundColor: "DarkViolet",
        },
      },
    },
  },

  defaultVariants: {
    variant: "gray",
  },
});

const Home = () => {
  const { theme, setTheme } = useTheme();
  const toggleTheme = () => setTheme(theme === "light" ? "dark" : "light");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Text as="h1" size="3">
          The current theme is {theme === "dark" ? "dark" : "light"}
        </Text>
        <Button onClick={toggleTheme}>Change Theme</Button>
        <Button onClick={toggleTheme}>Change Theme</Button>
        <Button variant={"purple"} onClick={toggleTheme}>
          Button Purple
        </Button>
      </main>
    </div>
  );
};
Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
